version: '3.4'

services:
  rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:management
        hostname: "rabbitmq"
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
        networks:
          - rabbitmq_network
        healthcheck:
          test: ["CMD", "rabbitmqctl", "status"]
          interval: 10s
          retries: 5
          start_period: 10s

  rabbitmq_masstransit_cqrs.producer:
        image: ${DOCKER_REGISTRY-}rabbitmqmasstransitcqrsproducer
        build:
          context: .
          dockerfile: RabbitMq_MassTransit_CQRS.Producer/Dockerfile    
        depends_on:
          rabbitmq:
            condition: service_healthy
        environment:
          - RABBITMQ_HOST=rabbitmq
        networks:
          - rabbitmq_network  

  rabbitmq_masstransit_cqrs.consumer:
        image: ${DOCKER_REGISTRY-}rabbitmqmasstransitcqrsconsumer
        build:
          context: .
          dockerfile: RabbitMq_MassTransit_CQRS.Consumer/Dockerfile
        depends_on:
          rabbitmq:
            condition: service_healthy
        environment:
          - RABBITMQ_HOST=rabbitmq
        networks:
          - rabbitmq_network
   
networks:
  rabbitmq_network:
    driver: bridge

